# Generated by Django 5.1.3 on 2024-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('action_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.JSONField(default=list)),
                ('assigned_to', models.JSONField(default=list)),
                ('is_assigning', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('required_bot_count', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
