# Generated by Django 5.1.3 on 2024-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_data',
            field=models.JSONField(default=dict),
        ),
    ]
